version: '2'

services:
  mysql:
    restart: on-failure
    image: mysql:5.7
    container_name: db_server
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=url_db
      - MYSQL_LOG_CONSOLE=true
    volumes:
      - ./config_files/dbsetup.sql:/docker-entrypoint-initdb.d/dbsetup.sql
      - ./config_files/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  nginx:
    restart: always
    build:
      context: .
      dockerfile: dockerfile-nginx
    image: nginx
    container_name: web_server
    volumes:
      - ./config_files/nginx_site.template:/etc/nginx/conf.d/nginx_site.template
      - ./web_app/static:/usr/share/nginx/html
    ports:
      - "80:80"

  app-engine:
    restart: always
    build:
      context: .
      dockerfile: dockerfile-app
    image: app-accelerator
    container_name: app_server
    links:
      - nginx
      - mysql
    volumes:
      - ./web_app:/web_app
    ports:
      - "81:80"
      - "5001:5001"
